@startuml
hide circle
hide empty members

class Reparatiekaart {
    - klant: String 
    - voertuigType: VoertuigType
    - reparatie: ArrayList<String>
    - tijd: Number 
}

enum VoertuigType <<Enumeration>> {
    Fiets 
    Scooter 
}
@enduml